version: "3"

services:

  react:
    build: react
    ports:
      - 3000:3000
    volumes:
      - ./react:/app
    command: npm run dev
    depends_on:
      - strapi

  strapi:
    build: strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - HOST=localhost
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
    ports:
      - 1337:1337
    restart: always
    volumes:
      - ./strapi/app:/usr/src/api/strapi-app
    depends_on:
      - mongo

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/sh:/data/sh
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - DATABASE_NAME=strapi

  # nginx:
  #   build: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 81:81
  #     - 82:82
  #   depends_on:
  #     - react
  #     - strapi
