
version: "3"

services:

  strapi:
    build: strapi
    environment:
      - APP_NAME=strapi-app
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - HOST=localhost
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
      # - DATABASE_USERNAME=
      # - DATABASE_PASSWORD=
    ports:
      - 1337:1337
    volumes:
      - ./strapi/app:/usr/src/api/strapi-app
    depends_on:
      - mongo
    restart: always

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/sh:/data/sh
    environment:
      - MONGO_INITDB_DATABASE=strapi

  # react:
  #   build: react
  #   ports:
  #     - 3000:3000
  #   volumes:
  #     - ./react:/app
  #   command: npm run dev
  #   # depends_on:
  #   #   - strapi
