version: "3"

services:

  react:
    image: node:10
    working_dir: /app/react
    volumes:
      - ./react:/app/react
    ports:
      - 3000:3000
    command: npm run dev
    depends_on:
    - hapi

  hapi:
    build: hapi
    working_dir: /app/hapi
    volumes:
      - ./hapi:/app/hapi
    ports:
      - 8000:8000

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/bin:/data/bin
    environment:
      - MONGO_INITDB_DATABASE=hapi
      - DATABASE_NAME=hapi

  # nginx:
  #   build: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 3000:3000
  #     - 8000:8000
  #   depends_on:
  #     - react
  #     - strapi
