version: "3"

services:

  react:
    build: react
    volumes:
      - ./react:/usr/react
    ports:
      - 3000:3000

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/sh:/data/sh
    environment:
      - MONGO_INITDB_DATABASE=dating
      - DATABASE_NAME=dating

  api:
    build: api
    ports:
      - 3333:3333
    volumes:
      - ./api/app:/usr/src/api/api
    depends_on:
      - mongo
    restart: always
    # environment:
    #   - APP_NAME=api
    #   - DATABASE_CLIENT=mongo
    #   - DATABASE_HOST=mongo
    #   - HOST=localhost
    #   - DATABASE_PORT=27017
    #   - DATABASE_NAME=strapi

  # nginx:
  #   build: nginx
  #   volumes:
  #     - .///
