version: "3"

services:

  # it's more easy to run in localy the user interface
  # react:
  #   build: react
  #   volumes:
  #     - ./react:/usr/react
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #   - hapi

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/bin:/data/bin
    # environment:
    #   - MONGO_INITDB_DATABASE=hapi
    #   - DATABASE_NAME=hapi

  # nginx:
  #   build: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 81:81
  #     - 82:82
  #   depends_on:
  #     - react
  #     - strapi
