version: "3"

services:

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/sh:/data/sh
    environment:
      - MONGO_INITDB_DATABASE=dating
      - DB_NAME=dating

  api:
    image: node:10.0.0
    ports:
      - 3333:3000
    working_dir: /usr/api
    volumes:
      - ./api:/usr/api
    depends_on:
      - mongo
    restart: always
    command: npm run launch

  react:
    image: node:10.0.0
    ports:
      - 3000:3000
    working_dir: /usr/react
    volumes:
      - ./react:/usr/react
    depends_on:
      - api
    command: npm run launch
