version: "3"

services:

  react:
    build: react
    volumes:
      - ./react:/usr/react
    ports:
      - 3000:3000
    depends_on:
    - strapi

  # 15/12/2018
  # login ui strapi : benoit.arguel@gmail.com
  # password ui strapi : Scoopc12
  strapi:
    build: strapi
    environment:
      - APP_NAME=strapi
      - DATABASE_CLIENT=mongo
      - DATABASE_HOST=mongo
      - HOST=localhost
      - DATABASE_PORT=27017
      - DATABASE_NAME=strapi
    ports:
      - 1337:1337
    volumes:
      - ./strapi/app:/usr/src/api/strapi
    depends_on:
      - mongo
    restart: always

  mongo:
    build: mongo
    ports:
      - 27017:27017
    restart: always
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/bin:/data/bin
    environment:
      - MONGO_INITDB_DATABASE=strapi
      - DATABASE_NAME=strapi

  # nginx:
  #   build: nginx
  #   volumes:
  #     - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
  #   ports:
  #     - 81:81
  #     - 82:82
  #   depends_on:
  #     - react
  #     - strapi
